### ISSUE TITLE
view cluster no-op or importer mode 

### ISSUE THREAD

**Issue by WentaoJin** [pingcap/tidb-lightning#134]
## Feature Request

**Is your feature request related to a problem? Please describe:**

After using tidb-lightning, can not confirm tidb cluster current mode is no-op or importer mode 

**Describe the feature you'd like:**

tidb-lightning is missing command to view cluster no-op or importer mode

**Comment by kennytm** [comment]
The "import mode" setting is tracked directly by each TiKV node, and the current value isn't exposed by any API yet. There is currently a PR for TiKV 3.0 tikv/tikv#4206 which will eventually expose such metrics to Prometheus. After that PR is merged, we could use the metrics to distinguish between the two modes.

| Metric label (`tikv_config_rocksdb{name="…"}`) | Normal mode | Import mode |
|--------|-------------|-------------|
| `level0_stop_writes_trigger` | small (36) | large (2<sup>30</sup>) |
| `level0_slowdown_writes_trigger` | small (20) | large (2<sup>30</sup>) |
| `soft_pending_compaction_bytes_limit` | large (64 GiB) | 0 |
| `hard_pending_compaction_bytes_limit` | large (256 GiB) | 0 |
