### ISSUE TITLE
Is it possible to add vendor directory?

### ISSUE THREAD

**Issue by loveleon** [pingcap/tidb-lightning#135]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
We've recently removed the vendor directory as cleanup (#122). Unless there's a strong reason, we don't intend to bring them back.
