### ISSUE TITLE
Fast import from SST files

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-lightning#155]
## Feature Request: Fast import from SST files

Request: the fastest possible import from backup with the least amount of resource usage.

One use case for this that I have in mind is to import a vary large example dataset as quickly as possible.

Currently lightning imports from a mydumper backup. The process of converting mydumper to SST files takes time and resource intensive. I would like to pay the cost once (or skip mydumper altogether).

In theory we can just save the intermediate SST files. In practice, there are issues to work through:

> if you have saved the `data.import` directory after an engine file is written but before it is cleaned up, you could run `tidb-lightning-ctl --import-engine <UUID>` to directly ingest those SSTs again. However, the KV pairs include the Table ID, which afaik cannot be controlled in a CREATE TABLE statement
> we need some development, such as controlling not to clean up these ssts,  saving the checksum of these ssts, and using the specified table ID (which also means you have to control the table version).

@morgo @c4pt0r

**Comment by kennytm** [comment]
Note that if the purpose is to do a physical backup of the TiDB database, there's also going to be a TiKV-based solution using Raft Learner (tikv/rfcs#11).

**Comment by gregwebs** [comment]
Yes, these solutions have overlap. I don't know what the status of physical backup is (from the RFC status it seems that we will still not have it for quite some time?).
On the other hand, this feature request seems relatively straightforward. There may be some benefits in testability (it will be easier to test just the import step) that would justify having this feature in lightning even when we have physical backup.

**Comment by kennytm** [comment]
With BR I think we can close this issue?
