### ISSUE TITLE
NATS support

### ISSUE THREAD

**Issue by gedw99** [pingcap/tidb-lightning#190]
I noticed that Kafka can be used as a sink.

Would NATS be welcomed ?

I think it's a nice complimentary message queue as it's 100% golang, fast and HA / durable 

I think it would be easy to implement also as NATS is very simple API and has API client in golang .

**Comment by kennytm** [comment]
Hi, thanks for interest. But do you mean to file the feature request at https://github.com/pingcap/tidb-binlog? Lightning is a data import tool, while Binlog is the CDC tool.

**Comment by gedw99** [comment]
It's for reacting to changes in the TiDb database

**Comment by kennytm** [comment]
Yes, so you'll need TiDB Binlog instead of Lightning.

**Comment by gedw99** [comment]
Closing. Will make new issue at Lightening..
