### ISSUE TITLE
Restore from NFS protocol

### ISSUE THREAD

**Issue by ericsyh** [pingcap/tidb-lightning#194]
## Feature Request

**Describe the feature you'd like:**
Similar feature request with https://github.com/pingcap/tidb-lightning/issues/69
Support restore sql backup file through NFS protocol

**Describe alternatives you've considered:**

We need to consider the below situations:
1. Customers don't agree to put their DB backup in public cloud like aws s3, alicloud oss.
2. Customer don't have private cloud of distributed storage, like Ceph.

Under these situations,  we cannot support with the S3 store.

**Comment by ericsyh** [comment]
@kennytm Kenny actually i think this issue should be closed cause BR is currently more suitable for this situation:
* If customer want to bakcup TiDB, they should BR rather mydumepr currently and BR support NFS & S3. 
* If customer want to import MySQL to TiDB, mydumper will dump the files on local disk, will no need for TiDB-Lightning to import from NFS.
What u think?

**Comment by kennytm** [comment]
LGTM (since you could mount the NFS drive to the file system anyway.)

**Comment by ericsyh** [comment]
Agreed to close.
