### ISSUE TITLE
使用TIDB-Lightning进行.csv文件导入时，表示找不到对应的table info 

### ISSUE THREAD

**Issue by MRLUHUIZHONG** [pingcap/tidb-lightning#195]
请问下这种情况可能是什么原因造成的呢？
error:/home/jenkins/workspace/build_tidb_lightning/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:323: table info table_XXX not found

table 的数据文件名称为 db.table_name.csv
表示无论将文件名改成什么样都无法正常识别呢？？？

**Comment by kennytm** [comment]
Hi,

You will also need a `db.table_name-schema.sql` file to describe the table's schema. It should contain a CREATE TABLE statement.

Alternatively, if you have already created the table on TiDB, you could set `[mydumper] no-schema = true` to skip this.

**Comment by MRLUHUIZHONG** [comment]
其实，已经那么设置了呢！表是可以创建的，no-schema 后来设置为 true了。不过以db.table_name.csv 
就是加载不了数据呢！一直在报table info XXX not found ,已经崩溃了，最近一直在分析你们的源码呢！
不过还是很谢谢你的回复呢！

**Comment by kennytm** [comment]
You're welcome 😊.

Have you checked if the file names and table names are having the same case? (e.g. maybe the table was named `` `DB`.`TABLE_NAME` `` which currently won't match a file named `db.table_name.csv`)

**Comment by MRLUHUIZHONG** [comment]
文件命名也对着呢٩(๑^o^๑)۶，数据文件名为test.user.csv用来测试的呢！谢谢您的回答呢！不过文件命名和配置都没问题呢，都是按照官方文档来配的呢！所以很苦恼呢(๑ó﹏ò๑)！发自我的华为手机-------- 原始邮件 --------主题：Re: [pingcap/tidb-lightning] 使用TIDB-Lightning进行.csv文件导入时，表示找不到对应的table info  (#195)发件人：kennytm 收件人：pingcap/tidb-lightning 抄送：MRLUHUIZHONG ,Author You're welcome 😊.

Have you checked if the file names and table names are having the same case? (e.g. maybe the table was named `DB`.`TABLE_NAME` which currently won't match a file named db.table_name.csv)

**Comment by MRLUHUIZHONG** [comment]
1.数据文件是这个样子的呢！
-rw-r--r-- 1 root root      44 5月  28 11:16 user-schema-create.sql
-rw-r--r-- 1 root root    2598 5月  28 11:17 user.xwj0014_history-schema.sql
-rw-r--r-- 1 tidb tidb  736569 5月  28 13:41 user.xwj0014_history.sql
2.部分lightning配置是这个样子的：
batch-import-ratio = 0.75
# mydumper 源数据目录。
data-source-dir = "/home/tidb/data/backup"
no-schema = true
character-set = "auto"
[mydumper.csv]
# 字段分隔符，应为单个 ASCII 字符。.csv 用 ‘，’ .tcv 用 ‘\t’
separator = ','
# 引用定界符，可为单个 ASCII 字符或空字符串。
delimiter = '"'
# CSV 文件是否包含表头。
# 如果为 true，第一行导入时会被跳过。
header = true
# CSV 是否包含 NULL。
# 如果 `not-null` 为 true，CSV 所有列都不能解析为 NULL。
not-null = false
# 如果 `not-null` 为 false（即 CSV 可以包含 NULL），
# 为以下值的字段将会被解析为 NULL。
null = '\N'
# 是否解析字段内反斜线转义符。
3.importer配置：

job = "tikv-importer"
# 给 Prometheus 客户端的推送间隔。
interval = "15s"
# Prometheus Pushgateway 地址。
#address = ""
[rocksdb]
# 最大的背景任务并发数。
max-background-jobs = 32
[rocksdb.defaultcf]
# 数据在刷新到硬盘前能存于内存的容量上限。
write-buffer-size = "1GB"
# 存于内存的写入缓冲最大数量。
max-write-buffer-number = 8
# 各个压缩层级使用的算法。
# 第 0 层的算法用于压缩 KV 数据。# 第 6 层的算法用于压缩 SST 文件。
# 第 1 至 5 层的算法目前忽略。
compression-per-level = ["lz4", "no", "no", "no", "no", "no", "zstd"]
[import]
# 存储引擎文档 (engine file) 的文件夹路径。
import-dir = "/home/tidb/tidb-v2.1.9/bin"
# 处理 gRPC 请求的线程数量。
num-threads = 16
# 导入任务并发数。
num-import-jobs = 24
# 预处理 Region 最长时间。
max-prepare-duration = "5m"
# 把要导入的数据切分为这个大小的 Region。
region-split-size = "512MB"
# 流管道窗口大小，管道满时会阻塞流。
stream-channel-window = 128
# 引擎文档同时打开的最大数量。
max-open-engines = 8

基本上配置就是这个样子了，引擎文件的目录不知道怎么填，并没有发现有引擎文件的目录。然后库、表、都是可以创建的呢？

报错情况基本如下：
2019/05/28 15:42:59.286  [error] [step 2] run cause error : table info xwj0014_history not found
2019/05/28 15:42:59.286  [info] the whole procedure takes 55.401436ms
2019/05/28 15:42:59.286 main.go:65: [error] tidb lightning encountered error:table info xwj0014_history not found
github.com/pingcap/tidb-lightning/lightning/restore.(*RestoreController).restoreTables

说是没找到 数据表,然后就感觉数据表校验这块是不是有什么规则、或者什么要求呢？
谢谢啦！！！求帮助呢！

**Comment by MRLUHUIZHONG** [comment]
原因找到了呢！表名中含有“_”这个特殊字符的情况下数据库中的表无法正常识别呢，然后在数据表和库表比对的情况下匹配不到呢！
还是很谢谢你们呢！😊😊😊😊😊

**Comment by kennytm** [comment]
@MRLUHUIZHONG Nice that you've found the cause 😃. However I don't think that `_` is really the cause of error, as our test cases contain lots tables with an `_` in it ([example](https://github.com/pingcap/tidb-lightning/blob/master/tests/various_types/data/vt.empty_strings-schema.sql)).

(With `no-schema = true`, the tables need to be manually created on TiDB, i.e. 

```sql
SHOW CREATE TALBE `user`.`xwj0014_history`;
```

should print something before running TiDB Lightning.)

**Comment by MRLUHUIZHONG** [comment]
最后又排查了一遍，原来是数据文件的表名大小写问题。DDL文件中table _name为大写，数据文件的命名为小写匹配不上。后来，都改为小写的表名再测试就好了！看来这块TIDB也严格要求大小写规范呢！😅😅😅谢谢啦朋友！

**Comment by kennytm** [comment]
I see, thanks for checking :). I'll close this as a duplicate of #143 then.

**Comment by MRLUHUIZHONG** [comment]
嗯，谢谢您的帮助呢！😊😊😊😊😊

**Comment by andylulu** [comment]
![image](https://user-images.githubusercontent.com/6284029/62524471-48dc0880-b868-11e9-8a98-5aeb3376fb19.png)
为啥我的日志中显示没报错，导入完成后数据库表中竟然没数据

**Comment by kennytm** [comment]
@andylulu Hi, could you file a new issue instead of reusing this one? Thanks.
