### ISSUE TITLE
err:rpc error: code = Unknown desc = ResourceTemporarilyUnavailable("Too many open engines)

### ISSUE THREAD

**Issue by evancao77** [pingcap/tidb-lightning#196]
## Question
version:
tidb-lightning 2.1.9
tidb  2.1.4

When I import data with tidb-lightning, After the time, the error is as follows：
2019/05/30 07:41:43.841  [info] [`PAYBASEDIMENSION`.`TRANSLOG`] import whole table takes 13h11m33.936320627s
2019/05/30 07:41:43.841  [error] [`PAYBASEDIMENSION`.`TRANSLOG`] error rpc error: code = Unknown desc = ResourceTemporarilyUnavailable("Too many open engines 04fab71b-13e6-5e2f-ad64-fb4fae56229e: 8")
2019/05/30 07:41:43.841  [info] restore all tables data takes 13h11m34.086283344s
2019/05/30 07:41:43.841  [error] run cause error : rpc error: code = Unknown desc = ResourceTemporarilyUnavailable("Too many open engines 04fab71b-13e6-5e2f-ad64-fb4fae56229e: 8")
2019/05/30 07:41:43.841  [info] the whole procedure takes 13h11m34.119171179s
2019/05/30 07:41:43.841 restore.go:399: [info] Everything imported, stopping periodic actions
2019/05/30 07:41:43.852 main.go:65: [error] tidb lightning encountered error:rpc error: code = Unknown desc = ResourceTemporarilyUnavailable("Too many open engines 04fab71b-13e6-5e2f-ad64-fb4fae56229e: 8")
github.com/pingcap/errors.AddStack
	/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
	/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb-lightning/lightning/kv.(*Importer).OpenEngine
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-lightning/lightning/kv/importer.go:178
github.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).restoreEngine
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:648
github.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).restoreTable.func1
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:588
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337

When I restarted, it worked fine, but after a while I reported the same error. How to solve this problem, how can I ensure that the data is not lost?

thinks for help

**Comment by kennytm** [comment]
Hi,

Please ensure the `max-open-engine` setting on tikv-importer (currently 8) is larger than `index-concurrency` (should be 2) + `table-concurrency` (should be 6). Please try to reduce `table-concurrency` and start Lightning again. You may find instructions on [Lightning's Troubleshooting docs](https://pingcap.com/docs/dev/how-to/troubleshoot/tidb-lightning/#resourcetemporarilyunavailable-too-many-open-engines-8).

---

> how can I ensure that the data is not lost?

Restarting Lightning won't cause data loss (if checkpoints is enabled).

Restarting Importer (if necessary) may cause tables still being written from Lightning (i.e. "opened engines") to be lost; they will be removed after restarting Importer. You may check by

```sh
ls -la /data/deploy/data.import/.temp
#      ^-----------------------^
#       same as tikv-importer's `import-dir` setting
```

If this `.temp` directory is empty, it is safe to restart Importer without losing data.

**Comment by evancao77** [comment]
thanks for your help
