### ISSUE TITLE
Improve usability: automatically solve invalid checkpoint

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb-lightning#241]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In some case (tencent PCG, e.g.) user maybe need to choose 'destroy' or 'ignore' invaid checkpoints. Those decisions may solved by code in some situation, for example:

1. invalid status came from or after `CHECKSUMED` should continue running
2. at TiDB Backend, imported rows could use `count(*)` difference of break time and start time to check correctness

So we may provide this auto-solve option, consume some time, to reduce user's decision.

**Describe the feature you'd like:**

auto-solve option for invalid checkpoint in `tidb-lighting-ctl`

**Describe alternatives you've considered:**

auto-solve option in `tidb-lightning`, triggered at detected invalid checkpoints.

or user guide.

**Teachability, Documentation, Adoption, Optimization:**

`--checkpoint-error-auto-solve` of `tidb-lightning-ctl`

**Comment by kennytm** [comment]
Closing, replaced by #286.
