### ISSUE TITLE
Error 1105: privilege check fail

### ISSUE THREAD

**Issue by wangchong666** [pingcap/tidb-lightning#265]
lightning log
```
[2020/01/30 00:17:49.929 +08:00] [WARN] [util.go:95] ["compute remote checksum failed but going to try again"] [table=`tmp`.`presale_20200227`] [query="ADMIN CHECKSUM TABLE `tmp`.`presale_20200227`"] [retryCnt=0] [error="Error 1105: privilege check fail"]

```

**Comment by kennytm** [comment]
Executing ADMIN CHECKSUM TABLE currently requires "SUPER" privilege.

**Comment by wangchong666** [comment]
@kennytm thanks for replay,How to grant "SUPER" privilege? I can not  find anthing about this in the document.Do I have to use `root` in the lightning?

**Comment by kennytm** [comment]
Using `root` account is the simplest solution. Since TiDB Lightning writes to TiKV directly which skips privilege check, using TiDB Lightning is the same as using root anyway.

You could also grant SUPER privilege to any user by running this in `mysql` as root:

```sql
GRANT SUPER ON *.* TO myuser;
```

and revoke it later by:

```sql
REVOKE SUPER ON *.* FROM myuser;
```
