### ISSUE TITLE
*: use new row-format in tidb

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/tidb-lightning#267]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB v4.0 uses new row format https://github.com/pingcap/tidb/blob/master/docs/design/2018-07-19-row-format.md format, lightning should also update to use new row format

**Describe alternatives you've considered:**

It is best to use the tidb library functions to construct row data directly, so that you only need to update the tidb version in the future.

**Comment by GregoryIan** [comment]
@kennytm @3pointer  please pay attention

**Comment by kennytm** [comment]
Lightning doesn't construct the row directly. It uses TiDB's `(Table).AddRecord` method to convert `[]types.Datum` into KV pairs. So I think upgrading TiDB dependency is enough to transition to the new format.

**Comment by kennytm** [comment]
Changes to use the new format:

1. Upgrade TiDB to include pingcap/tidb#12634
2. Set the system var `@@tidb_row_format_version` to 2.

Perhaps we can fetch the value automatically for step 2 from downstream TiDB.

**Comment by GregoryIan** [comment]
Ok, if `Datum ` is not changed, `(Table).AddRecord` is  safe
