### ISSUE TITLE
cannot decode settings from TiDB

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#277]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
start lightning without pd-addr config on tidb backend
2. What did you expect to see?
no error
3. What did you see instead?
```
[error="cannot decode settings from TiDB, please manually fill in `tidb.port` and `tidb.pd-addr`: json: cannot unmarshal bool into Go struct field Log.log.enable-slow-log of type uint32"]
```
4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        >  v4.0.0-beta.1
                
    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

         >  v4.0.0-beta.1

**Comment by kennytm** [comment]
This particular error should be fixed by #281. But then it is incompatible with old TiDB where `enable-slow-log` was still a int. I'll stop using `tidbcfg.Config` instead.
