### ISSUE TITLE
support collations

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb-lightning#284]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tidb/projects/33

after we support collations, the kv encode may different according to the collation.
so we must update lightning to learn what collation and encoding in the right way according to the collation.

there might some compatible issues too.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by glorv** [comment]
@kennytm  shall we prioritise this issue? There is user case met this issue now? https://asktug.com/t/topic/37458/12

And I think we can follow #268, fetch `new_collation_enabled` from mysql.tidb and if enabled, set `collate.EnableNewCollations()`, then the generated kv will be new collation

**Comment by kennytm** [comment]
SGTM.
