### ISSUE TITLE
Implement data and index kv sort in lightning

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#290]
## Feature Request

**Is your feature request related to a problem? Please describe:**

To remove importer component. we need to split & scatter region in lightning before generate sst, so the sortkv need to confirm first.

**Describe the feature you'd like:**

1.  add new abstract backend(local)
2. writeRows to local and sort (maybe use goleveldb or something)

**Describe alternatives you've considered:**

1. data kvs can sort partly but index kvs need sort globally

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
Note: This is part of #300. Close?

**Comment by kennytm** [comment]
Local backend has been implemented, considered fixed.
