### ISSUE TITLE
Implement split & scatter in lightning

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#291]
## Feature Request

**Is your feature request related to a problem? Please describe:**

after #290, we need split & scatter region before send kvs to TiKV peers.

**Describe the feature you'd like:**

port split & scatter from current importer.

**Describe alternatives you've considered:**

maybe we can abstract split & scatter logic, both BR and Lightning can reuse this  

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
Note: This is part of #300. Close?

**Comment by kennytm** [comment]
Local backend has been implemented, considered fixed.
