### ISSUE TITLE
Support restoring VIEWs and SEQUENCEs

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-lightning#297]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB and MariaDB both support VIEW and SEQUENCE, but Lightning is unable to import them yet. This makes restoring/migrating an SQL backup tedious, as the VIEW and SEQUENCE have to be manually reconstructed.

**Describe the feature you'd like:**

Support restoring VIEW and SEQUENCE, or its general form, pre-create-table SQLs and post-create-table SQLs.

SEQUENCEs must be created before tables are created, because tables may use `NEXT VALUE FOR seq` as the default value.

VIEWs must be created after tables are created, since the structure of the views depend on the tables (in mydumper and mysqldump, VIEWs are first created as tables to define the name and structure, and then dropped and replaced by the real VIEW definition.)

**Describe alternatives you've considered:**

-

**Teachability, Documentation, Adoption, Optimization:**

-

**Comment by kennytm** [comment]
One potential issue of sequences is that we can't reliably determine the implied values of missing columns, since the sequence can be shared.

```sql
create sequence s;
create table a (c int default nextval(s));
create table b (c int default nextval(s));
insert into a values (), (), (), ();
insert into b values (), (), ();
insert into a values (), (), (), (), ();
insert into b values (), ();
```

**Comment by IANTHEREAL** [comment]
@pcqz Can you help describe the unreasonable situation that users are encountering now?

**Comment by pcqz** [comment]
The user exported tables and views from MySQL to TiDB v4.0 using lightning. The table and view definition(desensitized) in MySQL is as follows.

```
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `col1` int(11) DEFAULT NULL,
  `col2` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `col3` int(11) NOT NULL,
  `col4` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `col5` double NOT NULL DEFAULT 0,
  `col6` double NOT NULL DEFAULT 0,
  `col7` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `col8` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `col9` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `col10` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `col11` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `col12` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `test_col2_col1` (`col2`,`col1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=779857;

CREATE VIEW `test_view`
AS SELECT
   `test`.`id` AS `id`,
   `test`.`col1` AS `col1`,
   `test`.`col2` AS `col2`,
   `test`.`col3` AS `col3`,
   `test`.`col4` AS `col4`,
   `test`.`col7` AS `col7`,
   `test`.`col5` AS `col5`,
   `test`.`col6` AS `col6`,
   `test`.`col8` AS `col8`,
   `test`.`col10` AS `col10`,
   `test`.`col11` AS `col11`,
   `test`.`col12` AS `col12`
FROM `test`;
```

When `test_view` imported into TiDB, the definition become innodb table instead of view, and all columns are int(11).

```
CREATE TABLE `test_view` (
  `id` int(11) DEFAULT NULL,
  `col1` int(11) DEFAULT NULL,
  `col2` int(11) DEFAULT NULL,
  `col3` int(11) DEFAULT NULL,
  `col4` int(11) DEFAULT NULL,
  `col7` int(11) DEFAULT NULL,
  `col5` int(11) DEFAULT NULL,
  `col6` int(11) DEFAULT NULL,
  `col8` int(11) DEFAULT NULL,
  `col10` int(11) DEFAULT NULL,
  `col11` int(11) DEFAULT NULL,
  `col12` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

**Comment by IANTHEREAL** [comment]
@glorv @kennytm Please give a solution for the unexpected behavior `When test_view imported into TiDB, the definition become innodb table instead of view, and all columns are int(11).`

**Comment by kennytm** [comment]
we'll start working on it after #366 is merged.

**Comment by IANTHEREAL** [comment]
OK Such good news, you should tell me in advance 😆
