### ISSUE TITLE
Lightning add local backend

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#300]
This `local` backend allow user to use `Lightning` independent without `Importer`.
After https://github.com/tikv/tikv/pull/7459 finished, `Lightning` has the ability to write to TiKV alone.

we have follow things to do:
- [x] add local backend for lightning (#326)
- [x] optimize local backend performance (#334, #338)
- [x] add test plan for local backend (https://github.com/pingcap/automated-tests/pull/412)
- [x] update related docs

**Comment by overvenus** [comment]
@glorv Please update the issue, thanks!

**Comment by glorv** [comment]
@3pointer  @kennytm shall we mark this issue as finished?
