### ISSUE TITLE
`check-requirements` failed when tiflash is enabled

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-lightning#301]
## Bug Report

When `check-requirements` is enabled, tidb-lightning will check the version info of store in PD, tiflash is also registered in PD as a store, but the version of tiflash is `v4.1.0-alpha-27-ge7c6dedc3`, so the check will fail.

**Comment by kennytm** [comment]
@tennix which  version of Lightning are you using?

**Comment by kennytm** [comment]
The Lightning used seems to not contain #295.

#295 is included in v3.0.14, v3.1.1, and the to-be-release v4.0.0-rc.2.
