### ISSUE TITLE
Avoid reusing checkpoint when backend or table ID changed

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-lightning#302]
When switching from TiDB backend to Local/Importer backend, the recorded checksum values become invalid. This would lead to strange checksum error. 

We should make the checkpoint invalid if the backend is changed (and probably other parameters too).

**Comment by glorv** [comment]
So We should save `backend` info to checkpoint and when resume from checkpoint, if backend mismatch, reports an error and exit?

**Comment by kennytm** [comment]
yes
