### ISSUE TITLE
Progress is inaccurate (overestimating time taken) when reusing checkpoint

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-lightning#303]
Repro steps:

1. Import some large database, long enough for the progress log to appear
2. Ctrl+C before all tables are written
3. Resume from checkpoint
4. Note that the remaining time is very long, as it includes those files already processed.

**Comment by glorv** [comment]
I think there are two different problems that affect the accuracy:
1. we resume from checkpoint we don't consider chunks already finished restore.
    - this can be easily fixed by adjust the estimate logic
2. how to estimate the extra time needed for import data with local/importer backend 
    - not sure if there is easy way
