### ISSUE TITLE
Don't use strict sql-mode as default

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#323]
## Feature Request

**Is your feature request related to a problem? Please describe:**

some user will meet sql-mode related problem when create schema. most often is `NO_ZERO_IN_DATE`, `NO_ZERO_DATE`. since sql-mode is session level variable, so it can't be possible to get accurate sql-mode of table when upstream create it.

**Describe the feature you'd like:**

1. Remove some strict mode in default sql-mode.
2. Add a function to distinguish sql-mode by given schema.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Optimization:**

**Comment by kennytm** [comment]
What is not fixed by #316?

**Comment by 3pointer** [comment]
okay，It seems already fixed, let me close this issue
