### ISSUE TITLE
misleading log ("user terminated") may be report when the import is abnormal

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tidb-lightning#327]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    see <https://asktug.com/t/topic/34941>

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
       v4.0.0
        ```
        

5. Operation logs

    ```
    [2020/06/02 15:28:14.249 +08:00] [INFO] [restore.go:266] ["user terminated"] [step=2] [error="restore table `pay`.`pay_purchase` failed: rpc error: code = Canceled desc = Cancelled"]
    ```

**Comment by kennytm** [comment]
change the message from "user terminated" to "task canceled".
