### ISSUE TITLE
tidb lightning encountered error

### ISSUE THREAD

**Issue by zhangdan1** [pingcap/tidb-lightning#341]
tidb lightning encountered error:  Error 1193: Unknown system variable 'allow_auto_random_explicit_insert'

**Comment by kennytm** [comment]
This has been fixed in #328 and will be present in the next Lightning release.

**Comment by zhangdan1** [comment]
The Lightning release I used is v4.0.1 , is  it fixed?

**Comment by kennytm** [comment]
@zhangdan1 no, v4.0.1 is released before #328. It will be included in v4.0.2, v3.1.2 and v3.0.16.

**Comment by zhangdan1** [comment]
thanks
