### ISSUE TITLE
Support load from file without formatted file name

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb-lightning#344]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we just support pass a folder with Mydumper-formatted files. This is in someway too "heavy", and some of other tools like `sqlldr` can load arbitrary file directly with command-line arguments.

Support importing arbitrary file will make life easier when we want to load some "incremental" csv data using TiDB backend.

**Describe the feature you'd like:**

add some flags:
- `-from-file` specifies a set of file to load
- `-to-table` specifies which table to load into
- `-to-db` specifies which database to load into

**Describe alternatives you've considered:**

We can rename those files directly and then load them with our "happy path", but renaming files isn't easy sometimes...

**Teachability, Documentation, Adoption, Optimization:**

When `-from-file` presents, we can load file and schema info from `-from-file`, `-to-table`, `-to-db` directly (omit the MyDumper folder), and `-no-schema` implies.

Then everything go on as normal.

**Comment by kennytm** [comment]
@YuJuncen: are we allowed to *only* use config files for "to-db" and "to-table"?

**Comment by YuJuncen** [comment]
> @YuJuncen: are we allowed to _only_ use config files for "to-db" and "to-table"?

Why...?

**Comment by kennytm** [comment]
in order to use [RFC 5](https://docs.google.com/document/d/1n4wSDcjgkF84Q9GApeWXsrw3fK42JYm40atz5zzTVLY/edit#heading=h.9gvmf1fxnd4l)

**Comment by YuJuncen** [comment]
Seems RFC 5 can cover this scenario without changing any code, cool.

Let me check it, if that is OK, this issue can be closed.

**Comment by kennytm** [comment]
if that is OK it means we need to schedule to implement RFC 5 (currently it is just a proposal but no work has started yet).

**Comment by YuJuncen** [comment]
Some of users prefer command line arguments, since it could be easier to use and to learn.

Implementing RFC 5 would spend some time, how about firstly implement `-from-file` first, then after RFC 5 implemented, redirect those flags to RFC 5, leave those flags as a "shortcut" of file routing for some trivial cases.

**Comment by YuJuncen** [comment]
(Or if no more requirement, we can keep delaying implementation of RFC 5...)

**Comment by kennytm** [comment]
can we close given #366 ?

**Comment by glorv** [comment]
@YuJuncen PTAL?

**Comment by YuJuncen** [comment]
> can we close given #366 ?

Of course.
