### ISSUE TITLE
checksum fails easily by tikv timeout when restore big table with local backend

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb-lightning#365]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When uses lightning to restore big table with local backend, I have seem several times in lightning logs with follows:
```
[2020/08/05 21:05:39.713 +08:00] [ERROR] [main.go:82] ["tidb lightning encountered error stack info"] [error="restore table `test`.`t` failed: compute remote checksum failed: Error 9002: TiKV server timeout"] 
```

And further more, in some benchmark, after finishing load data, when manually exec `select count(*) from table` with big table, the select may fail with:
```
mysql> select count(*) from t;
ERROR 1105 (HY000): Execution terminated due to exceeding the deadline
```

By consulting @breeswish ,  The root cause for this is that tikv process subtask in one region execeeded 1 minute, Either because the region is too large or the task waited for too long.

I thinking the primary cause of this is that  With local backend, region key range is not accurate the size of 96M, thus maybe some region is too big.

2. What did you expect to see?
checksum should success without retry and select count(*) should return successfully

3. What did you see instead?

4. Versions of the cluster

5. Operation logs
   
6. Configuration of the cluster and the task
   

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by lance6716** [comment]
https://internal.pingcap.net/jira/browse/TIDB-4758

for your reference
