### ISSUE TITLE
import successfully but checksum failed with wrong CSV header

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb-lightning#370]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Genrate data with go-tpc tpcc csv files. Then import data with tidb-lightning delimeter='"'.

2. What did you expect to see?
Import failed at the very beginning.

3. What did you see instead?
Failed after a table's checksum stage. When importing a large amount of data, this could be really frustrating for users. They'll wait for a long time to meet the failure

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        $ ./bin/tidb-lightning -V
        Release Version: v4.0.3-9-gf18863a-dev
        Git Commit Hash: f18863a6efe8ae16c5e84b4d11094c7e485ceb38
        Git Branch: master
        UTC Build Time: 2020-08-13 06:25:22
        Go Version: go version go1.14.7 linux/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by kennytm** [comment]
@cyliu0 i don't see setting the delimiter to `"` is relevant, since `abc,def,ghi` without delimiter will still be correctly parsed into 3 fields.

**Comment by cyliu0** [comment]
> @cyliu0 i don't see setting the delimiter to `"` is relevant, since `abc,def,ghi` without delimiter will still be correctly parsed into 3 fields.

Yes, but the checksum will not be passed.

**Comment by kennytm** [comment]
please copy the error message here?

**Comment by cyliu0** [comment]
```
[2020/08/12 17:27:11.236 +08:00] [INFO] [split_client.go:289] ["split region meet not leader error, retrying"] ["retry times"=0] [regionID=134120] ["new leader"="id:134121 store_id:1 "]
Error: restore table `test`.`warehouse` failed: checksum mismatched remote vs local => (checksum: 7608668812818337001 vs 0) (total_kvs: 1 vs 39900) (total_bytes:25 vs 997500)
tidb lightning encountered error:  restore table `test`.`warehouse` failed: checksum mismatched remote vs local => (checksum: 7608668812818337001 vs 0) (total_kvs: 1 vs 39900) (total_bytes:25 vs 997500
```

**Comment by kennytm** [comment]
this looks more like unique key violation. are there 39900 warehouses with different warehouse IDs?

**Comment by glorv** [comment]
I have met this failure and @3pointer  also met it today when run with tpcc data. After update the delimeter from '"' to '' I can run successfully. Maybe this is caused by recent changes, I'll look into this later

**Comment by kennytm** [comment]
i've checked the original source. lightning was invoked with the default `mydumper.csv.header = true`, but the CSVs generated by `go-tpc` contains no headers.

```console
[root@localhost data]# head test.warehouse.0.csv
1,DVpWp5N,6wmYWxoy0KX6JuvUM,FQFSqoKNFhMDrU,RKF9v0YrNEPB5,YP,793011111,0.066900,300000.000000
101,qWI2JXA3I,CWM2PGbo4bBRg6TNuN2l,IpOx2EvJE6VuZrOJCN,WdgqzrAX4a27eJt32AO,YJ,277711111,0.008400,300000.000000
201,Hs5OBy,Ci2oZA9apZss5iYERWqm,oR1TYOm3SH81Pjk,MPrSHFtQ4s,FA,725611111,0.178000,300000.000000
```
