### ISSUE TITLE
Support clustered index

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-lightning#388]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently when clustered index is enabled, the `_tidb_rowid` column is missing (?) and causes test failure. 

**Describe the feature you'd like:**

Support clustered index.

**Describe alternatives you've considered:**

No alternatives.

**Teachability, Documentation, Adoption, Optimization:**

**Comment by glorv** [comment]
So we should update all the tests to not depend on `_tidb_rowid` anymore, right?

**Comment by kennytm** [comment]
some tests involving `_tidb_rowid` are dedicated, so they should be kept.

more importantly the KV encoder should understand a table has clustered index and adjust the session accordingly, since that affects the row encoding.

**Comment by kennytm** [comment]
Local backend supports common handle in #367, but we should better verify for importer and tidb backend as well.

**Comment by glorv** [comment]
> Local backend supports common handle in #367, but we should better verify for importer and tidb backend as well.

Since importer/local share the same kv encoder, importer should also be supported new. the `common_handle` integration test is running with importer backend.
As for tidb backend, I think if there is no `_tidb_rowid` column in the source file, cluster index should be supported automatically.

**Comment by kennytm** [comment]
Not sure about TiDB backend since it involves reconstructing a `TableInfo` back from the `SHOW CREATE TABLE`.

**Comment by tangenta** [comment]
`SHOW CREATE TABLE` shows nothing about the clustered index. This is controlled by the session&global variable `tidb_enable_clustered_index`.

**Comment by kennytm** [comment]
yes.

in any case, expanding the `common_handle` test case to include the other two backends, and also make the table use more than one file should be sufficient

**Comment by glorv** [comment]
> 2. also make the table use more than one file, and
What does this mean?

**Comment by kennytm** [comment]
have a `ch.t.1.sql` in additional to `ch.t.0.sql`
