### ISSUE TITLE
Try to create tables in parallel

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb-lightning#434]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently we perform CREATE TABLE (`tidbMgr.InitSchema`) in sequence. But experiences in BR shows that running them in parallel is faster pingcap/br#377

**Describe the feature you'd like:**

Execute the CREATE TABLE in `restoreSchema` in parallel over 16 connections.

Benchmark that by importing 300 small tables.

**Describe alternatives you've considered:**

Don't do it.

**Teachability, Documentation, Adoption, Optimization:**

N/A

## Score

600

## SIG slack channel
[sig-migrate](https://slack.tidb.io/invite?team=tidb-community&channel=sig-migrate&ref=github_sig)

## Mentor

@glorv @lance6716

**Comment by hidehalo** [comment]
@kennytm shall we label it `sig-migrate`?

**Comment by lance6716** [comment]
> @kennytm shall we label it `sig-migrate`?

we're setting sig label for this whole repo in https://github.com/pingcap/tidb-lightning/pull/498 😄

**Comment by hi-rustin** [comment]
> @kennytm shall we label it `sig-migrate`?

Could you please try pick up again?

**Comment by hi-rustin** [comment]
> /cc @hi-rustin maybe later?

Try it when #498  megred.

**Comment by glorv** [comment]
@hidehalo Please try again~

**Comment by lance6716** [comment]
BTW, there's a similar issue in DM https://github.com/pingcap/dm/issues/717 . We'll be happy if you could take a look after this one (will add learning material and score later)

**Comment by hidehalo** [comment]
> BTW, there's a similar issue in DM [pingcap/dm#717](https://github.com/pingcap/dm/issues/717) . We'll be happy if you could take a look after this one (will add learning material and score later)

Thx!
