### ISSUE TITLE
. / lighting-ctl- fetch mode strongly depends on mydumper dir

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb-lightning#454]
tools version && cluster version: v4.0.8
![image](https://user-images.githubusercontent.com/21033020/98325148-14d23300-2029-11eb-8527-24cba4270792.png)

![image](https://user-images.githubusercontent.com/21033020/98325107-fcfaaf00-2028-11eb-992b-02e970c05be5.png)

This does not match the description in the document

![image](https://user-images.githubusercontent.com/21033020/98325274-5e228280-2029-11eb-8a07-4bf84b8b3352.png)

Please help to confirm, thank you

**Comment by kennytm** [comment]
fixed in #453.

**Comment by glkappe** [comment]
good job
