### ISSUE TITLE
Import parquet files too slow

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb-lightning#472]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Import 1.7G parquet files from s3

2. What did you expect to see?
Finished quickly

3. What did you see instead?
Didn't finish after 1 hour

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        ./bin/tidb-lightning -V
        Release Version: v4.0.8-13-g963829f-dev
        Git Commit Hash: 963829fd54f16ba135790bc8bde4b8c2d48fb1aa
        Git Branch: master
        UTC Build Time: 2020-11-12 07:05:29
        Go Version: go version go1.13.15 linux/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by glorv** [comment]
I ran two tests with the same dataset in a local cluster with minio and our dbaas environment. Both of them are much faster than this issue reported. (2m10s with minio, and 10m in dbaas environment)

**Comment by cyliu0** [comment]
With 170g+ parquet snapshot for 300g+ data on aurora, lightning cannot start importing for at least 30 mins. It looks like a huge issue for me. Could we improve the priority for this issue? I think this could be a blocker for our customers.
