### ISSUE TITLE
TiDB requires decimal for DOUBLE, caused CI failed

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb-lightning#473]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

after https://github.com/pingcap/parser/pull/1078 , `double(N)` is no longer supported, so we must specify a `D` representing "D digits may be after the decimal point". But our test in https://github.com/pingcap/tidb-lightning/blob/master/tests/various_types/data/vt.double.sql will get collision

2. What did you expect to see?

has a way to pass CI, but currently not since controller variable is not ready https://github.com/pingcap/tidb/pull/20967

3. What did you see instead?

CI can't pass

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        (paste TiDB-Lightning version here)
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by lance6716** [comment]
could we reduce the number range in https://github.com/pingcap/tidb-lightning/blob/master/tests/various_types/data/vt.double.sql @kennytm

**Comment by lance6716** [comment]
cc @AilinKid @overvenus

**Comment by kennytm** [comment]
@lance6716 we should just change the column type from `double(16)` to `double`.
