### ISSUE TITLE
Add open fd check for local backend 

### ISSUE THREAD

**Issue by overvenus** [pingcap/tidb-lightning#494]
## Bug Report

Import fails with `[checkpoints.go:1089] ["save checkpoint failed"] [error="open /tmp/tidb_lightning_checkpoint.pb: too many open files"] [errorVerbose="open /tmp/tidb_lightning_checkpoint.pb: too many open`

We should add a check before doing actual import.

**Comment by kennytm** [comment]
what is be the minimal fd value?

**Comment by glorv** [comment]
https://github.com/pingcap/tidb-lightning/blob/8a276c0282e59a1783c223b8c6e2bf1990025921/lightning/lightning.go#L653-L678

We have checked the minimal open file limit, seems the current check is not accurate.

**Comment by overvenus** [comment]
Here is how TiKV checks fd

https://github.com/tikv/tikv/blob/0d8f178d71caf1cf2d1e289821d04ac20217a6ae/cmd/src/server.rs#L1037-L1041

**Comment by glorv** [comment]
close by #501
