### ISSUE TITLE
log: error log is not clear.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb-lightning#513]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
restore data from s3. 

2. What did you expect to see?
successful or a clear error

3. What did you see instead?
```
Error: restore table `xxx`.`xxx` failed: AccessDenied: Access Denied
    status code: 403, request id: xxx, host id: xxx
tidb lightning encountered error:  restore table `xxx`.`xxx` failed: AccessDenied: Access Denied
```
this error looks like access denied from s3. but if not familiar with s3 errors. user will get confused about why tidb denied. so It's better to wrap it with a clear error.

4. Versions of the cluster
master

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

**Comment by lichunzhu** [comment]
It's hard to inter from lightning's result that whether the import operator is successful.
```bash
$ ./bin/tidb-lightning -c bin/lightning.toml
Verbose debug logs will be written to /var/folders/sr/_hc37vmj0db6ht4_w6rw34880000gn/T/lightning.log.2020-12-09T11.17.57+0800

tidb lightning exit
$ echo $?
0
```

**Comment by kennytm** [comment]
looks like we just need to wrap some errors with `errors.Annotate`.
