### ISSUE TITLE
Lightning report `[tikv:9002]TiKV server timeout` when analyze enabled

### ISSUE THREAD

**Issue by shuijing198799** [pingcap/tidb-lightning#518]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Lightning will failed for `[tikv:9002]TiKV server timeout` when analyze enabled
2. What did you expect to see?
lightning import completed
3. What did you see instead?
failed
4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
Release Version: v4.0.8-42-g59cc48d
Git Commit Hash: 59cc48d738c237c1bedfa2c758f905828369736e
Git Branch: master
UTC Build Time: 2020-11-26 12:45:03
Go Version: go version go1.13.8 linux/amd64
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
Release Version:   4.0.8
Edition:           Community
Git Commit Hash:   30001da180ba2408b905df061a10a73e482a8172
Git Commit Branch: HEAD
UTC Build Time:    2020-12-07 09:03:56
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec
Profile:           release
        ```

**Comment by cyliu0** [comment]
Reproduced on 4.0.9

**Comment by cyliu0** [comment]
Reproduced on 4.0.9 while importing 4TB tpcc data

**Comment by Little-Wallace** [comment]
Closed by https://github.com/pingcap/tidb-lightning/pull/540
