### ISSUE TITLE
Restore from S3 compatible API?

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb-lightning#69]
A feature request for your roadmap:

Can it be possible to restore directly from a mydumper backup stored in S3?  In most cloud deployments this is where user backups will be stored (the S3 API is implemented by many other object stores).

**Comment by tennix** [comment]
Is there any update on this? To be more cloud-native, we need to support restoring from S3 storage. Though we have a workaround in tidb-operator to use `rclone` to download all backup files locally and then feed to tidb-lightning, it's time-consuming and not user friendly (users cannot determine how large a PV should be required).

**Comment by overvenus** [comment]
For the AWS Aurora scenario, Aurora exports data in CSV format, and it is partitioned into multiple files. It's worth taking into consideration. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.SaveIntoS3.html#AuroraMySQL.Integrating.SaveIntoS3.Grant

**Comment by kennytm** [comment]
🤔 Partitioning into multiple files isn't a problem (it is actually *desired*). The problem is the file name does not end in `*.csv`.

```
s3-region://bucket-name/file-prefix.part_00000
```

**Comment by overvenus** [comment]
Can lightning choose file format based on its content?

Also, Aurora can export data into TEXT format, and the name is the same as the CSV format.

**Comment by kennytm** [comment]
it can but i don't trust Lightning to do so 🙂.

perhaps we need RFC 5 anyway.

**Comment by glorv** [comment]
> Also, Aurora can export data into TEXT format, and the name is the same as the CSV format.

Seems `TEXT` format likes CSV format, but use TAB as the delimiter and write the raw value for each field. So It's not a very good format, e.g. if some string fields contains TAB, then it's hard to distigulish which `TAB`s are the delimiter and which are field values. So we should recommend customers to use csv instead of text.

**Comment by glorv** [comment]
> it can but i don't trust Lightning to do so 🙂.
> 
> perhaps we need RFC 5 anyway.

Shall we provide an option to allow use explicitly set the input files format to `csv` or `sql` if they are not end with them.
Or we may support the sepcial pattern for s3's file partition pattern like `part_0000`. In the future, if we support read from compressed files,  we should also support partitioned compression files like `schema.table.csv.001.tar.gz`

**Comment by glorv** [comment]
> it can but i don't trust Lightning to do so 🙂.
> 
> perhaps we need RFC 5 anyway.

Seems if we want to support partitioned files in s3 buckets or partitioned compression files,  RFC 5 needs to be updated. And I afraid if the route rule is complex, it will be hard to teach user to use this feature

**Comment by overvenus** [comment]
For Aurora partition dump, Lightning could read Aurora dump manifest directly.

**Comment by kennytm** [comment]
That is a large departure from the existing model (`walkdir` the directory to discover files), so I regard the manifest file support as low priority.
